### ISSUE TITLE
Request: Please add shared client and server side validation (or compatible hooks) soon...

### ISSUE THREAD

**Issue by kristianmandrup** [derbyjs/racer#131]
Thanks!

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
