### ISSUE TITLE
Add browser-side tests

### ISSUE THREAD

**Issue by SLaks** [derbyjs/racer#133]
Can you set up [testing](https://ci.testling.com/) to run unit tests in browsers on build?

This is a great way to make sure that you don't accidentally break IE support.

To prevent it from running server-only store tests, you can make a `describeServer` wrapper method that does something like 

``` js
if (!process.browser) cb();
```

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
