### ISSUE TITLE
Remove/Insert of filtered item on ref'd filter causes faulty updates

### ISSUE THREAD

**Issue by cjblomqvist** [derbyjs/racer#145]
Example app which highlights the issue and includes a workaround:

View (/views/app/index.html):
```html
<Body:>
  <ul>{#each _page.items as :item}<li>{:item.nr}</li>{/}</ul>
```

App (/lib/app/index.js):
```javascript
var app = require('derby').createApp(module)
    ;

// Routes
app.get('/*', function(page, model, params, next) {
  page.render('');
});

app.enter('/*', function(model) {
  rows = [
     {
        "nr":1,
        "show":false
     },
     {
        "nr":2,
        "show":true
     },
     {
        "nr":3,
        "show":true
     }
  ];

  model.set('_page.data', rows);

  // Create filter
  app.filter = model.filter('_page.data', function(item) {
    return item.show;
  });

  app.filter.ref('_page.items');

  console.log('Error will occur below');

  model.remove('_page.data', 0); // Trigger error

  // Fixes issue (we expect [2, 3], but get [2, 2])
  if(false) {
    app.filter.model.removeRefList(app.filter.from);
    app.filter.ref(app.filter.from);
  }
});

// Routes
app.ready(function(model) {
  window.app = app;
  window.model = model;
});
```

The issue is that the refList updates, but also the actual data albeit nothing has really changed in that end. This is because the removed or added, in this example removed, item was already filtered out or will be filtered out - thus not affecting the actual filtered data.

The workaround triggers a complete refiltering and resetting of the filtered path, thus avoiding this issue. However, both as it is, and especially with the workaround, a lot of data is shuffled around and a lot of view updates are done without them being needed.

Will make tests and update my PR with a fix and reference this issue.

**Comment by enjalot** [comment]
closing this as model.filter doesn't support arrays anymore (see discussion in the closed PR)
