### ISSUE TITLE
extraRef to $count query not updating fully after deleting all records in collection

### ISSUE THREAD

**Issue by taijiren** [derbyjs/racer#170]
google groups thread here https://groups.google.com/forum/#!topic/derbyjs/1pcDUKSiuDI

Using the following functionality to get a live count of records in a collection...

countQuery = model.query 'my_collection',
  $count: true
  $query: {}
countQuery.extraRef '_page.myCollectionCount'

shows a correct count as records are added and deleted except when:
- records have been added
- then all records are deleted using model.del() on each
  the count at '_page.myCollectionCount' should show zero, but it doesn't. If the record deletes are done slowly enough, the count will be accurate right up until the last record is deleted. The count will stay at 1. If the record deletes are done quickly enough, the count will be some number between the number of records, N, and 1 (probably N-1?).

If, after all records have been deleted, the page is reloaded, then the count will show zero as it should.

Regardless of what $query is specified in the query object above, this seems to affect the ref'd count only if all of the records in the unfiltered collection are deleted (as opposed to deleting all of the records in the subset specified in the query).

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
