### ISSUE TITLE
Server side events

### ISSUE THREAD

**Issue by icaliman** [derbyjs/racer#183]
Events aren't triggered properly on the <b><i>server side</i></b>.

I generated a simple derby@0.5 project and added this code in <code>lib/server/index.js</code>

<pre>
var model = store.createModel();

model.subscribe("items", function(err) {
  if (err) throw err;

  model.on("all", "items**", function() {
    console.log("CHANGED ITEMS");
  });
});
</pre>

In the browser I have:
<pre>
...
model.add('items', newItem);
...
model.del('items.' + item.id);
</pre>

First issue is that <code>CHANGED ITEMS</code> message is shown only when I remove an item.
The second is that  not every time when I remove an item I see <code>CHANGED ITEMS</code> message.

I need to see this message server side on every <code>model.add</code> and <code>model.del</code> operations.

**Comment by enjalot** [comment]
we aren't supporting 0.5 anymore. can you reproduce in 0.6?
