### ISSUE TITLE
shareDoc.on() callback called multiple times

### ISSUE THREAD

**Issue by ile** [derbyjs/racer#189]
I ran into a problem where this callback is called multiple times on the same operation: https://github.com/derbyjs/racer/blob/master/lib/Model/RemoteDoc.js#L22

I didn't find the code where these callbacks are removed. Are they actually removed somewhere?

If they are, there still seems to be some bug as it seems that they are not always removed. This same callback is called multiple times in some cases.

If needed, I can try to come up with a test case, but if you can spot the problem right away, that would also be good.

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
