### ISSUE TITLE
data set on client even when preValidateWrite denies it

### ISSUE THREAD

**Issue by ile** [derbyjs/racer#192]
The data seems to be set on the client even if I deny it on preValidateWrite (https://gist.github.com/nateps/02d0b0293880905476bd).
- It's not set on the server, there is nothing on the Mongodb.
- It will also be cleared on the client if I do a hard refresh.

This is easy to test, just needs to set some data on the client, inspect if it's there. I did this:

``` html
<button type="button" on-click="setSomeData()">setSomeData</button>
```

``` coffeescript
#subscribe, do the ref() etc ... and ...

setSomeData: -> @model.root.set '_page.test.hi', 'there'
```

So, prevalidate denies this and nothing gets through, but stays locally until I do the hard refresh.

How to check the data is another matter, just `{{_page.test}}` won't update automatically, not sure why, but I have to do a "soft refresh" - click a link that renders the page locally.

This looks like a bug to me?

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
