### ISSUE TITLE
livedb store error

### ISSUE THREAD

**Issue by cometta** [derbyjs/racer#193]
var options = { db: {

        db: require('livedb-mongo')(mongoconn, {safe: true})
        ,redis: redis,redisObserver: redisObserver
       }
    };

    this.store = racer.createStore(options);

//when createstore called, i get below error
   throw Error('If you want to use redis, you need to instantiate the redis d
          ^
Error: If you want to use redis, you need to instantiate the redis driver separately and provide it to livedb via driver:livedb.redisDriver(db, redis, redisObserver
    at Error (<anonymous>)

**Comment by gurdasnijor** [comment]
Getting the same issue here; I had to fall back to:

```javascript

racer.createStore({
      db: require('livedb-mongo')(mongoconn, {safe: true}),
      redis: redis
  });

```
Which isn't optimal since I wanted to pass the redisObserver in explicitly

**Comment by enjalot** [comment]
see the updated derby-starter for an example of how do do this properly. sorry for the lack of docs on this change
https://github.com/derbyjs/derby-starter/blob/master/lib/server.js#L47
