### ISSUE TITLE
Item subscription is dropped in certain cases

### ISSUE THREAD

**Issue by ile** [derbyjs/racer#195]
An app (modified derby-examples/directory) to reproduce with:

https://github.com/ilkkah/d-test4

Derby bug is this: sometimes the subscription for an item is dropped too soon. This happens about 10 % of the time.

Reproduce like this:
- Add some (5-10) people into the directory
- Follow some/all of those people (click the follow button)
- Go to the Followed page
- Click a person, you'll see the edit page
- Click Unfollow. At this point, if the bug happens, the person info will go blank i.e. person data subscription is "dropped".
- If the bug doesn't happen, go to Followed page and select another person etc.

This should happen at least 10 % of the time (once in 10 persons).

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
