### ISSUE TITLE
Document already exists

### ISSUE THREAD

**Issue by ile** [derbyjs/racer#198]
This throws the error: http://todos.derbyjs.com/derby/

```
Ignoring attempt to ingest data in state floating doc.js:212
Operation was rejected (Document already exists). Trying to rollback change locally. doc.js:321
Error: Document already exists {stack: (...), message: "Document already exists"} microevent.js:45
Uncaught Error: Document already exists events.js:27
```

Seems like a Sharejs issue but I'm creating it here as I'm not sure if it's only Sharejs related.

Added it also [here](https://github.com/derbyjs/derby-examples/issues/50) but since this seems important I'm adding it here also.

Added it here too: https://github.com/share/ShareJS/issues/346

**Comment by enjalot** [comment]
are you still seeing this error?

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
