### ISSUE TITLE
"Unhandled document message"

### ISSUE THREAD

**Issue by SimonDegraeve** [derbyjs/racer#205]
On the todo example, with two windows, I add a new todo in the first window an I got this error in the second window:
```
Unhandled document message: Object {
  c: "groups",
  d: "home",
  data: Object,
  docName: "f1454ce1-122e-4d02-9034-306b23c30456",
  m: Object,
  type: "http://sharejs.org/types/JSONv0",
  v: 1
} 
```
Just before the error I receive the `sub` action correctly in this second window.
I suppose its because this message doesn't have any `a` property, but I dont know where is it triggered.

**Comment by enjalot** [comment]
we are looking into this. seems like a problem with the reactive subscribe on the todo documents

**Comment by gurdasnijor** [comment]
Ran into this same issue in a different context;

Seems like attempting to `subscribe()` after an `unsubscribe()` clears the previous subscription causes the issue.

It doesn't seem to show up if a `fetch()` or `subscribe()` happens on the server that initially bootstraps the data

**Comment by gurdasnijor** [comment]
Possibly fixed here?

https://github.com/share/ShareJS/commit/c2efe7a9d65a42e4c1ba1663748708f5c5a20314

**Comment by enjalot** [comment]
this is just a problem with using old racer-browserchannel causing an edge case in the way it transports messages.
