### ISSUE TITLE
'insert' event not capture when I push data into array?

### ISSUE THREAD

**Issue by jarvys** [derbyjs/racer#206]
Model structure is like:

``` Javascript
{
     "pages": [{
        "nodes": [
        ]
     }]
}
```

I register an insert listener on `pages.0.nodes`. When I  insert a node into `pages.0.nodes`, the modelListener go into `testFn` function as the code below:

``` JavaScript
function modelListener(segments, eventArgs) {
    var captures = testFn(segments);
    if (!captures) return;

    var args = (captures.length) ? captures.concat(eventArgs) : eventArgs;
    cb.apply(null, args);
    return true;
}
```

`testFn` source code:

``` JavaScript
function testPattern(segments) {
    // Any pattern with more segments does not match
    var patternLen = patternSegments.length;
   ...

    if (patternLen === segments.length || endingRest) {
      var captures = [];
      for (var i = 0; i < patternLen; i++) {
       ...
        if (patternSegment !== segment) return;
      }
     ...
    }
  };
```

Function `testFn` returns `undefined` and my listener is not called, because `segments` and `patternSegments`  are not the same!  `patternSegments` is `["pages", 0, "nodes"]`. But `segments` is `["pages", "0", "nodes"]`. The reason is that the second element of `patternSegments` is cast to integer by `util.castSegments`.

**Comment by enjalot** [comment]
hi @jarvys thanks for submitting this bug!
Any chance you would be willing to submit a PR given you found the root cause?
thanks!

**Comment by jarvys** [comment]
OK
