### ISSUE TITLE
Changes throws "mutation on uncreated remote document"

### ISSUE THREAD

**Issue by atoftegaard** [derbyjs/racer#224]
I am sorry for posing this here, but there seems to be no attention to issues in the demos repository.I have already created an issue [here](https://github.com/derbyjs/racer-examples/issues/4).

Both the pad and todos example throws the "mutation on uncreated remote document" exception. For the pad, it happens at each change to the textarea. For the todos, it happens on page load.

Both mongodb and redis seems to run as expected. However, I see no collections for either example application.

What is wrong?

**Comment by aliksend** [comment]
Sorry, I probably can't help you with it, 'cos I don't use redis. 
I can explain this issue that racer still in alpha version.
But you can use it and it working good with derbyjs, just follow [getting started in derbyjs website](http://derbyjs.com/started) and you can create first working application with racer and derby.

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
