### ISSUE TITLE
query.unsubscribe call callback twice

### ISSUE THREAD

**Issue by minicuper** [derbyjs/racer#225]
`model.unsubscribe(query, cb)` works perfect, but `query.unsubscribe(cb)` call cb twice

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
