### ISSUE TITLE
Racer null document instead of deleting it

### ISSUE THREAD

**Issue by mrThomasTeller** [derbyjs/racer#231]
http://dl.dropbox.com/u/79087675/20150729_0c69.png
Just try to delete any document using racer

**Comment by zag2art** [comment]
It's not a bug it's a feature :)

ShareJs should have a way to undo operations so it doesn't del docs to reserve the ids.

**Comment by mrThomasTeller** [comment]
@zag2art but if want to have unique indexes in MongoDB collection? They breaks down ShareJS.

**Comment by mrThomasTeller** [comment]
@zag2art Do you know, when ShareJS deletes empty documents completely?

**Comment by zag2art** [comment]
> Do you know, when ShareJS deletes empty documents completely?

Never, If you want to do this you should do it manually. F. e. you can use server hook to catch the del-operations and use mongo native driver to remove the docs completely - (see https://github.com/derbyparty/derby-hook del hook)

**Comment by mrThomasTeller** [comment]
>@zag2art but if I want to have unique indexes in MongoDB collection? They break down ShareJS.
I found that I should just add option "sparse" to unique index

**Comment by zag2art** [comment]
> I found that I should just add option "sparse" to unique index

Great

**Comment by mrThomasTeller** [comment]
Thank you! I guess it should be added to documentation if it wasn't.
