### ISSUE TITLE
Working example of angularjs app working with racer... for awhile

### ISSUE THREAD

**Issue by tajohnson661** [derbyjs/racer#235]
Hi all,

I've been trying to get racer to work with an angular app and have had some decent luck, but with an issue I can't seem to work out.  The only examples I've seen using angular seem way out of date, so I tried my own.  The code is at:

https://github.com/tajohnson661/racer-angular-example

There's a bunch of code in there from the samples provided, so thanks for that.  The problem in my example is that if I run the application for awhile, it'll eventually just hang/die/sit there doing nothing.  The app lets you go into two rooms, where each room has two textareas that are racer-enabled, so there are 4 total textareas under the control of racer.  If you switch between the rooms, it'll eventually get lost (for me, it's the 6th time).

Other than that, things seem to work great, and if I can get it to work fully, it'll be an awesome addition to the real app I'm working on.  Any help would be appreciated.

Thanks,
Tom

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
