### ISSUE TITLE
Exception in a model event subscription causes subscriptions break

### ISSUE THREAD

**Issue by balek** [derbyjs/racer#244]
If a callback for a mutation event throws an exception, all other mutation event callbacks stops working. That's because all future events go to the model.root._mutatorEventQueue, which wouldn't be handled:
https://github.com/derbyjs/racer/blob/master/lib/Model/events.js#L85-L100
I propose to wrap all callbacks with a try/catch block here:
https://github.com/derbyjs/racer/blob/master/lib/Model/events.js#L252
like it's done here:
https://github.com/derbyjs/racer/blob/master/lib/Model/events.js#L42-L46

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
