### ISSUE TITLE
Error message "Mutation on uncreated remote document"

### ISSUE THREAD

**Issue by zheoreh** [derbyjs/racer#247]
Please implement more clear message for this error i.e. add collection name and identifier. It's difficult to debug an error reason. Thnks

**Comment by niole** [comment]
Please implement clear repro for this problem, thanks.

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
