### ISSUE TITLE
State of Derby/Racer

### ISSUE THREAD

**Issue by ile** [derbyjs/racer#252]
Hi,

I'm wondering what the state of Derby is, are you planning to improve it further?

One big problem, imo, is the size of it. Of course that may be a difficult problem to solve, but it's several hundred kbs -- that hurts on mobile. 

Have you had the same experiences/do you have any plans to overcome this?

Thanks.

**Comment by ile** [comment]
Another nice thing to have would be a native iOS/Android version of Derby? :)

**Comment by plentylife** [comment]
i'm interested in this software as well, but don't want to commit to a dead project

**Comment by ile** [comment]
Bytecode for templates? https://engineering.linkedin.com/blog/2017/12/the-glimmer-binary-experience

**Comment by ile** [comment]
Offline usage with service workers...

**Comment by ile** [comment]
This could help with the native (ios/android) support: https://www.nativescript.org/
