### ISSUE TITLE
Modern examples

### ISSUE THREAD

**Issue by curran** [derbyjs/racer#290]
It would be great to see some modern examples. The [current reference examples](https://github.com/derbyjs/racer-examples) have not been updated in 5 years.

Sketch for what I'd like to see:
 * Built with Rollup
 * ES6 throughout
 * Use of WebSockets, not Browserchannel
 * An additional example showing a React integration

**Comment by curran** [comment]
Thank you @cray0000 for the pointer!

>React integration requires observables implementation like MobX to leverage the reactive programming paradigm of racer
I would be curious to try an integration without any additional libraries. I bet it is possible.

Are there any Racer examples out there that fall in between the [5 year old examples](https://github.com/derbyjs/racer-examples) and [StartupJS](https://github.com/startupjs/startupjs)?

The main thing I struggle with is the _basic setup_. For example, the examples [bundle client JS on demand](https://github.com/derbyjs/racer-examples/blob/master/pad/server.js#L24), and which is confusing. Also, it's not clear how to instantiate Racer without using Browserchannel.

**Comment by cray0000** [comment]
@curran `react-sharedb` is the standalone library which can be used independently from startupjs. You can refer to the following issue on the example to how to set it up:

https://github.com/startupjs/startupjs/tree/master/packages/react-sharedb#using-react-sharedb-in-a-pure-react-project

And if you feel like it you can make a PR there (to startupjs) or here (to racer) with an out of the box working example of pure racer and react integration using `react-sharedb`

**Comment by curran** [comment]
Thanks!

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
