### ISSUE TITLE
Date values set from the client side are persisted as strings

### ISSUE THREAD

**Issue by lackac** [derbyjs/racer#42]
I have noticed this with the MongoDB backend, but I suspect this applies to other adapters as well.

Steps to reproduce:
1. create a route which sets a date on some field: `model.set("users.42.updated_at", new Date())`
2. access this route directly from the server
3. look at the data persisted in the database, it should be something like this: `"updated_at" : ISODate("2012-09-20T11:57:07.637Z")`
4. now access this from the client side (e.g. with a link pointing to '/')
5. look at the data persisted in the database, it should be something like this: `"updated_at" : "2012-09-20T11:57:03.243Z"`

I suspect this is a side effect of how `JSON.stringify` and `JSON.parse` handles `Date` objects.

**Comment by lefnire** [comment]
@lackac you laughed, right? 2012?
