### ISSUE TITLE
Offline support using localStorage

### ISSUE THREAD

**Issue by bachp** [derbyjs/racer#46]
It would be nice to have a HTML5 localStorage back-end for racer. This would allow an application to work  in a truly offline fashion and still have the synchronization capability provided by racer.
I thought this could be similar to the mongodb back-end but on the client side.

The app would get bootstrapped the first time it connects to the server and it then can be used offline. The data would be stored persistently in the browser. As soon as the user is online again it gets synced back to the server as it would usually be done.

Maybe this is already possible using racer but I was not able to find anything about this.

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
